version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=barbershop_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    depends_on:
      - db
    tty: true  # позволяет интерактивный режим
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "admin" ]
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: