# Используйте официальный образ Python
FROM python:3.9

# Установите зависимости
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируйте всё приложение в контейнер
COPY . .

# Команда по умолчанию для запуска вашего приложения
CMD ["python", "docker-entrypoint.py"]